# Generated by Django 5.1.2 on 2024-11-22 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('obs', models.TextField()),
                ('horario', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'agendamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id_servico', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=15)),
                ('preco', models.FloatField()),
            ],
            options={
                'db_table': 'servico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id_vacina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('validade', models.DateField()),
                ('lote', models.CharField(max_length=45)),
                ('fab', models.DateField()),
            ],
            options={
                'db_table': 'vacina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('cnpj', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('crmv', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=45)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clinica',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.AutoField(primary_key=True, serialize=False)),
                ('nasc', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('peso', models.FloatField()),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('cpf', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('nasc', models.DateField()),
                ('senha', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tutor',
            },
        ),
        migrations.CreateModel(
            name='ConsultaRealizada',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('tipo_nota', models.CharField(max_length=1)),
                ('nota', models.TextField()),
                ('statuspet', models.CharField(db_column='statusPet', max_length=20)),
                ('pet_id_pet', models.ForeignKey(db_column='pet_id_pet', on_delete=django.db.models.deletion.DO_NOTHING, to='app_SUSA.pet')),
            ],
            options={
                'db_table': 'consulta_realizada',
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='tutor_cpf',
            field=models.ForeignKey(db_column='tutor_cpf', on_delete=django.db.models.deletion.DO_NOTHING, to='app_SUSA.tutor'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('clinica_cnpj', models.ForeignKey(blank=True, db_column='clinica_cnpj', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_SUSA.clinica')),
                ('tutor_cpf', models.ForeignKey(blank=True, db_column='tutor_cpf', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_SUSA.tutor')),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
